#this is a template of yml file
name: env_name
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xlrd=1.2
  - dash
  - requests
  - autograd>=1.3
  - hyperopt>=0.2.2
  - matplotlib>=3.1.1
  - numpy>=1.16.4
  - pandas>=1.0.1
  - scipy>=1.3.1
  - sqlalchemy
  - dill
  - psycopg2=2.7.7
  - scikit-learn>=0.22.2
  - nlopt>=2.6.2
